name: bingo
channels:
  - conda-forge
  - defaults
dependencies:
  - dill
  - mpi4py=4.1.0
  - numpy
  - scikit-learn
  - scipy
  - sympy
  - pytest
  - pytest-timeout
  - pip
  - h5py
  - pandas
  - pip:
    - smcpy
